# Partially generated by ChatGPT (08/09/2025)
import random
import numpy as np
import sys

def generate_workload(n, u):
    """
    Generate n distinct integers in [0, u].
    """
    if n > u + 1:
        raise ValueError("n cannot exceed the size of the universe (u+1).")

    return random.sample(range(u + 1), n)

if __name__ == "__main__":
    if len(sys.argv) <= 2:
        print("Usage: python program.py n u")
        sys.exit(1)

    n = int(sys.argv[1])
    u = int(sys.argv[2])

    workload = generate_workload(n, u)
    with open("workload.txt", "w") as f:
        for item in workload:
            f.write(f"{item}\n")