name: CMake (Linux, GCC & Clang, low memory)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
          - compiler: clang
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ clang libtbb-dev
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            sudo apt-get install -y libomp-dev
          fi

      - name: Configure CMake (optimize for low memory)
        run: |
          cmake -B build \
                -S . \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_CXX_FLAGS_RELEASE="-O2 -DNDEBUG" \
                -DCMAKE_C_FLAGS_RELEASE="-O2 -DNDEBUG"

      - name: Build (limited parallelism)
        run: cmake --build build -- -j2

      - name: Test
        working-directory: build
        run: ctest --output-on-failure
